[package]
name = "my-crate"
version = "0.1.0"
authors = ["Package Test <test@example.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "my_actual_crate"

[dependencies]
